apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth 
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::651783246143:user/azeez    # Update as needed with your IAM user ARN
      username: azeez    # Update as needed with your desired Kubernetes username
      groups:
        - system:masters    # Gives admin access to cluster